apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: webnginx
  name: webnginx
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    nodePort: 30080
  selector:
    io.kompose.service: webnginx
status:
  loadBalancer: {}
