apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - args:
        - bundle
        - exec
        - rails
        - server
        - -p
        - "3000"
        - -b
        - 0.0.0.0
        image: mariological/testapp
        name: app
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
